// login constants
const LOGIN_REQUEST='LOGIN_REQUEST'
const LOGIN_SUCCESS='LOGIN_SUCCESS'
const LOGIN_FAILED='LOGIN_FAILED'

//logout constant
const LOGOUT='LOGOUT'

//register constants
const REGISTER_REQUEST='REGISTER_REQUEST'
const REGISTER_SUCCESS='REGISTER_SUCCESS'
const REGISTER_FAILED='REGISTER_FAILED'





export {LOGIN_REQUEST,LOGIN_SUCCESS,LOGIN_FAILED,REGISTER_REQUEST,REGISTER_SUCCESS,REGISTER_FAILED,LOGOUT}
